name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'

    - name: Install coverlet
      run: dotnet tool install --global coverlet.console

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-incremental

    - name: Run tests and generate coverage report
      run: coverlet ./CovExample.Tests/bin/Debug/net6.0/CovExample.Tests.dll --target "dotnet" --targetargs "test --no-build" --format opencover --output ./coverage/coverage.xml

    - name: Setup SonarCloud
      uses: sonarsource/sonarcloud-github-action@v1.8
      with:
        projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
        organization: ${{ secrets.SONAR_ORGANIZATION }}
        token: ${{ secrets.SONAR_TOKEN }}

    - name: SonarCloud analysis
      run: |
        dotnet sonarscanner begin /k:"${{ secrets.SONAR_PROJECT_KEY }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths=./coverage/coverage.xml
        dotnet build --no-incremental
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"




