# This workflow will build a .NET projectt
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Inspect code
      uses: muno92/resharper_inspectcode@v1
      with:
        solutionPath: ./BrewingBuddies.sln
        minimumSeverity: error
      
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal
    - name: Restore NuGet packages
      run: dotnet restore

    - name: CD to BrewingBuddiesDirectory
      run: cd ~/BrewingBuddies-Back-end-
    - name: Change branch
      run: git checkout main
    - name: Pull changes
      run: git pull
    - name: Stop current docker container
      run: docker stop BrewingBuddies-Back-end-
    - name: Delete current docker container
      run: docker rm BrewingBuddies-Back-end-
    - name: Remove current web api Image
      run: docker rmi --force BrewingBuddies-Back-end-
    - name: Build the Docker image
      run: docker build --rm -t BrewingBuddies-Back-end- .
    - name: Run Docker container
      run: docker run -p 5000:5000 -p 5001:5001 -e ASPNETCORE_HTTP_PORT=https://+:5001 -e ASPNETCORE_URLS=http://+:5000 --name BrewingBuddies-Back-end- --restart=always BrewingBuddies-Back-end-
