# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Buildx docker
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Inspect code
      uses: muno92/resharper_inspectcode@v1
      with:
        solutionPath: ./BrewingBuddies.sln
        minimumSeverity: error
      
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal
    - name: Restore NuGet packages
      run: dotnet restore

    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Dockerhub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dionn/brewingbuddies:latest
        
  deploy_locally:
    name: Deploy Locally
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Pull Docker image
      run: docker pull dionn/brewingbuddies:latest
      
    - name: Run Docker container
      run: -p 5000:5000 -p 5001:5001 -e ASPNETCORE_HTTP_PORT=https://+:5001/ -e ASPNETCORE_URLS=http://+:5000/ --name BrewingBuddies --restart=always BrewingBuddies
      


