# This workflow will build a .NET projectt
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Docker operations
      run: |
        CD BrewingBuddies-Back-end-  # Change to the correct directory
        git checkout main
        git pull
        docker stop BrewingBuddies-Back-end- || true  # Stop container if running, ignoring errors if it's not running
        docker rm BrewingBuddies-Back-end- || true    # Remove container, ignoring errors if it doesn't exist
        docker rmi --force BrewingBuddies-Back-end- || true  # Remove image, ignoring errors if it doesn't exist
        docker build --rm -t BrewingBuddies-Back-end- .  # Build Docker image
        docker run -p 5000:5000 -p 5001:5001 -e ASPNETCORE_HTTPS_PORT=5001 -e ASPNETCORE_URLS=https://+:5001 --name BrewingBuddies-Back-end- --restart=always BrewingBuddies-Back-end-  # Run Docker container

    - name: Inspect code
      uses: muno92/resharper_inspectcode@v1
      with:
        solutionPath: ./BrewingBuddies.sln
        minimumSeverity: error
      
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --verbosity normal
    - name: Restore NuGet packages
      run: dotnet restore


