name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

  sonarqube:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup SonarQube Scanner
        uses: SonarSource/sonarqube-scan-action@v1
        with:
          sonar-login: ${{ secrets.SONAR_TOKEN }}
          sonar-project-key: BrewingBuddies
          sonar-host-url: http://localhost:9000
